export const SET_INITIAL_SCREEN = 'SET_INITIAL_SCREEN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';

export const GET_AUTH_USER = 'GET_AUTH_USER';
export const GET_AUTH_USER_SUCCESS = 'GET_AUTH_USER_SUCCESS';
export const GET_AUTH_USER_FAIL = 'GET_AUTH_USER_FAIL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
