export const SET_INITIAL_SCREEN = 'SET_INITIAL_SCREEN';
export const ADD_TODO = 'ADD_TODO';
export const CHANGE_NAME = 'CHANGE_NAME';
export const LOAD_QUIZZES = 'LOAD_QUIZZES';
export const LOAD_QUIZZES_SUCCESS = 'LOAD_QUIZZES_SUCCESS';
export const LOAD_QUIZZES_FAIL = 'LOAD_QUIZZES_FAIL';
